### ISSUE TITLE
Logic around already-closed indexes doesn't log cleanly

### ISSUE THREAD

**Issue by intjonathan** [reyjrar/es-utils#11]
This applies to version 2.9, which is the last available on RHEL 6. 

The following conditional only checks whether it got a status object back, then tries to evaluate the content of it even when it might not be meaningful.

https://github.com/reyjrar/es-utils/blob/release-2.9/scripts/es-daily-index-maintenance.pl#L174

The effect during a normal run is like so:
```
[root@production-elasticsearch-1 ~]# /usr/local/bin/es-daily-index-maintenance.pl --all --replicas-min 1 --local --pattern logstash-*
Use of uninitialized value in numeric gt (>) at /usr/local/bin/es-daily-index-maintenance.pl line 174.
Use of uninitialized value in numeric gt (>) at /usr/local/bin/es-daily-index-maintenance.pl line 174.
Use of uninitialized value in numeric gt (>) at /usr/local/bin/es-daily-index-maintenance.pl line 174.
```
Every closed index emits a warning line. Script runs fine, but stderr is really noisy. What it actually gets back from ES during that _status request is:
```
{"error":"IndexClosedException[[logstash-2014.11.07] closed]","status":403}
```
Which of course dosn't have a shards element. Probably another defined() call would clean it up.

**Comment by reyjrar** [comment]
Fixed in 3.5!
