### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [reyjrar/es-utils#12]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives. See also http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by reyjrar** [comment]
Thanks for the suggestion, I'll investigate migration for the next release.  FWIW, I've never encountered any issues with File::Slurp in my heavy use of the utility.

**Comment by reyjrar** [comment]
Replaced File::Slurp with Path::Tiny in 3.8 release.
