### ISSUE TITLE
Current --tail logic is unreliable for multi node clusters or multiple data sources with possible delays

### ISSUE THREAD

**Issue by timbunce** [reyjrar/es-utils#13]
The current `--tail` logic uses the simple condition: `range => {'@timestamp' => {gte => $last_hit_ts}}`

Let's assume that there is a cluster of 3 ES nodes, but only one source of data, and that data is in presented in `@timestamp` order. Elasticsearch sends the docs to be stored to different nodes. Those nodes will update the segments with the new docs within `refresh_interval` but the update is not synchronized across nodes. So the order in which docs 'become searchable' may not be in `@timestamp` order, so the `gte => $last_hit_ts` condition is not sufficiently safe. Older docs may be missed because they became 'searchable' after other docs that have a later `@timestamp`.

A fix for this might be something like:
- add the concept of a 'time window' eg `range => {'@timestamp' => {gte => $last_hit_ts - $time_window}}`
- record the document ids that have been seen in final time window from the last query
- exclude those document ids so they're not shown twice (either by including the ids in an extra NOT condition in the query, or else by checking and discarding duplicate ids in the client)

(The scope of the problem described above is bounded by the value of `refresh_interval` but other related situations aren't. Consider the case of multiple sources of data where some might be delayed. For example, we have many machines feeding logs to several logstash servers which feed an ES cluster. Logs are often delayed for at least a few seconds and sometimes for many minutes. Increasing the 'time window' approach described above doesn't scale well to larger time periods or high volumes of log messages. For this case the best approach would be to enable the [`_timestamp` field](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html) field and use that to drive the tailing logic.)

**Comment by clintongormley** [comment]
One correction: the `refresh_interval` is not an upper bound.  It merely determines how often a refresh will be started.  While refreshes are usually very fast, it is possible that they can take considerably longer than 1s, for instance when using eager global ordinals on very high cardinality fields.

We are planning to add a changes API which will solve this problem.  Unfortunately, this depends on first adding sequence IDs, which is quite a complicated task, so will take a while to make this happen.

**Comment by reyjrar** [comment]
I'll look into one of those solutions for the next release.

**Comment by reyjrar** [comment]
I haven't forgotten about this, but really, the only way to cleanly and completely accomplish it would be to have the equivalent of a SERIAL or PRIMARY KEY AUTO_INCREMENT. There's no clean way to ask ElasticSearch "give me all the documents you indexed after this one."  It's a free-text search engine, not a traditional RDBMS.  All the solutions I've come up with aren't "complete" or would require an in-memory cache of all seen documents and essentially record all ID's of documents seen and not advance to the next minute until all the previous minutes documents had been seen.

Given that, --tail is still interesting for low frequency events or to know "hey, yes, I'm indexing data" so I'm leaving it in the distribution.  But there's no easy way to fix this.
