### ISSUE TITLE
Fails with 500 and not much else...

### ISSUE THREAD

**Issue by bemeyert** [reyjrar/es-utils#15]
```
[root@salttestvm70 ~]# /usr/local/bin/es-copy-index.pl --debug --from other-host --to localhost logstash-2015.10.23
Failed to create index in localhost (http status = 500): [
   "500",
   {
      "error" : "NullPointerException[null]",
      "status" : 500
   }
]
 at /usr/local/bin/es-copy-index.pl line 75.
```

That's all although I turned on debugging.

**Comment by reyjrar** [comment]
You can try --debug --debug-class App::ElasticSearch::Utilities

**Comment by reyjrar** [comment]
Apologies for the slow turn around but I just started working closely with Elasticsearch after a bit of an absence.  I have not uploaded Version 4.1 to the CPAN yet, but the most recent master branch contains fixes for this script.  It is far more capable than it's ever been.

Please feel free to test/confirm yourself and let me know if it's missing anything.

See [the examples](https://github.com/reyjrar/es-utils/blob/master/CopyIndexes.mkdn#examples) section of the docs to get started!
