### ISSUE TITLE
No feature for name [_status]

### ISSUE THREAD

**Issue by duylong** [reyjrar/es-utils#21]
Hi, 

The index _status API has been replaced with the index _stats. I just change the attribute in the  "es-daily-index-maintenance.pl" script and it works again:

```
- my $status = es_request('_status',{index=>$index});
+ my $status = es_request('_stats',{index=>$index});
```

**Comment by reyjrar** [comment]
Added to VersionHacks.pm, this works in the release 5.0 I just pushed.
