### ISSUE TITLE
Apply settings after a few days

### ISSUE THREAD

**Issue by duylong** [reyjrar/es-utils#24]
Hi,

It would be nice to be able to use the es-apply-settings.pl script to apply parameters after a few days, and not just on the last days.

Best regards,

**Comment by reyjrar** [comment]
Working on that for the next release

**Comment by reyjrar** [comment]
The distribution already has the concept of an index is within the past few days, via the --days and --base index selectors.

We can experiment with a new option, maybe?
 `es-apply-settings.pl --older --days 30 --base logstash`

**Comment by duylong** [comment]
Hi,

Yes ! older it's a good option and meets my needs, 

In my case, I don't use base, only pattern option.

**Comment by duylong** [comment]
We can also add "younger" ? Knowing that the older and younger can not be used at the same time.

**Comment by reyjrar** [comment]
"younger" is the default, --older is the newer option, so there's really no need for --younger as it'd just be a noop.
