### ISSUE TITLE
Why perl 5.14.0 for version 3.0

### ISSUE THREAD

**Issue by labrown** [reyjrar/es-utils#8]
What is the reason to require Perl 5.14.0 or better for release version 3.0?

**Comment by intjonathan** [comment]
In the same boat here, which means I'm stuck on 2.9. RHEL 6 is still pretty widespread.

**Comment by reyjrar** [comment]
Reinvestigating :)

**Comment by reyjrar** [comment]
Going to use perlbrew to build and release with Perl 5.10.1, that will cover RHEL6.

**Comment by labrown** [comment]
Much appreciated!

--[Lance]

**Comment by reyjrar** [comment]
Corrected this by fixing the bug in es-search.pl that was forcing the minimum perl to 5.14.0 and hard coded minimum perl in dist.ini to prevent future releases from breaking RHEL6.
